#pragma once

/*
 *  Copyright (c) xEmbeddedTools team and contributors.
 *  Licensed under the Apache License, Version 2.0. See LICENSE file in the project root for details.
 */

#define XMCU_SOC_VENDOR_ST st
#define XMCU_SOC_ARCHITECTURE_ARM arm
#define XMCU_SOC_CORE_FAMILY_M4 m4
#define XMCU_SOC_VENDOR_FAMILY_WB wb
#define XMCU_SOC_VENDOR_FAMILY_RM0434 rm0434

#define XMCU_SOC_VENDOR XMCU_SOC_VENDOR_ST
#define XMCU_SOC_ARCHITECTURE XMCU_SOC_ARCHITECTURE_ARM
#define XMCU_SOC_CORE_FAMILY XMCU_SOC_CORE_FAMILY_M4
#define XMCU_SOC_VENDOR_FAMILY XMCU_SOC_VENDOR_FAMILY_WB
#define XMCU_SOC_VENDOR_FAMILY_RM XMCU_SOC_VENDOR_FAMILY_RM0434

#if defined(XMCU_SOC_MODEL_STM32WB35CEU6A) || defined(XMCU_SOC_MODEL_STM32WB55CGU6)
// AES
#define XMCU_AES1_PRESENT
#define XMCU_AES2_PRESENT

// GPIO
#define XMCU_GPIOA_PRESENT
#define XMCU_GPIOB_PRESENT
#define XMCU_GPIOC_PRESENT
#define XMCU_GPIOE_PRESENT
#define XMCU_GPIOH_PRESENT

// USART
#define XMCU_USART1_PRESENT

// LPUART
#define XMCU_LPUART1_PRESENT

// LPTIM
#define XMCU_LPTIM1_PRESENT
#define XMCU_LPTIM2_PRESENT

// I2C
#define XMCU_I2C1_PRESENT
#define XMCU_I2C3_PRESENT

// SPI
#define XMCU_SPI1_PRESENT

// TIM
#define XMCU_TIM1_PRESENT
#define XMCU_TIM2_PRESENT
#define XMCU_TIM16_PRESENT
#define XMCU_TIM17_PRESENT

// DMA
#define XMCU_DMA1_PRESENT
#define XMCU_DMA2_PRESENT

// clock sources
#define XMCU_HSE_PRESENT
#define XMCU_HSI16_PRESENT
#define XMCU_HSI48_PRESENT
#define XMCU_LSE_PRESENT
#define XMCU_LSI_PRESENT
#define XMCU_MSI_PRESENT
#define XMCU_PLL_PRESENT

// clocks
#define XMCU_CLK48_PRESENT
#define XMCU_HCLK_PRESENT
#define XMCU_PCLK_PRESENT
#define XMCU_SYSCLK_PRESENT
#endif

#if defined(XMCU_SOC_MODEL_STM32WB35CEU6A)
#define XMCU_FLASH_PAGE_SIZE 4096u
#define XMCU_FLASH_PAGES_COUNT 128u
#endif

#if defined(XMCU_SOC_MODEL_STM32WB55CGU6)
#define XMCU_FLASH_PAGE_SIZE 4096u
#define XMCU_FLASH_PAGES_COUNT 256u
#endif


#if defined(XMCU_SOC_MODEL_STM32WB55CGU6)
// SPI
#define XMCU_SPI2_PRESENT
#endif
